DELIMITER $$

CREATE DATABASE IF NOT EXISTS PR2 $$

USE PR2 $$

-- ASIGNACION DE TAGS A PUBLICACIONES
DROP TABLE IF EXISTS Tags_detail $$
CREATE TABLE Tags_detail (
	detail_id INTEGER NOT NULL AUTO_INCREMENT,
	tag_id INTEGER,
	pub_id INTEGER,
	PRIMARY KEY(detail_id)
) $$

-- LISTADO DE TAGS ALMACENADOS EN LA BASE DE DATOS
DROP TABLE IF EXISTS Tags $$
CREATE TABLE Tags (
	tag_id INTEGER NOT NULL AUTO_INCREMENT,
	name VARCHAR(255),
	
	PRIMARY KEY(tag_id)
) $$

-- COMENTARIOS QUE SE HAN HECHO A PUBLICACIONES
DROP TABLE IF EXISTS Comments $$
CREATE TABLE Comments (
	id_comment INTEGER NOT NULL AUTO_INCREMENT,
	content VARCHAR(255),
	comment_date DATETIME DEFAULT NOW(),
	pub_id INTEGER,
	email VARCHAR(255),
	
	PRIMARY KEY(id_comment)
) $$

-- PUBLICACIONES REALIZADAS
DROP TABLE IF EXISTS Publications $$
CREATE TABLE Publications (
	pub_id INTEGER NOT NULL AUTO_INCREMENT,
	image VARCHAR(255) NOT NULL,
	description VARCHAR(255),
	pub_date DATETIME DEFAULT NOW(),
	email VARCHAR(255),
	
	PRIMARY KEY(pub_id)
) $$

-- MENSAJES DE LAS CONVERSACIONES ENTRE USUARIOS Y BOTS
DROP TABLE IF EXISTS Chat_bots $$
CREATE TABLE Chat_bots (
	email VARCHAR(255) NOT NULL,
	sender VARCHAR(255),
	content VARCHAR(255),
	message_date DATETIME DEFAULT NOW()
) $$

-- MENSAJES DE CONVERSACIONES ENTRE AMIGOS
DROP TABLE IF EXISTS Chat_friends $$
CREATE TABLE Chat_friends(
	id_friendship INTEGER NOT NULL,
	sender VARCHAR(255),
	content VARCHAR(255),
	message_date DATETIME DEFAULT NOW()
) $$

-- LISTADO DE AMIGOS
DROP TABLE IF EXISTS Friends $$
CREATE TABLE Friends(
	id_friendship INTEGER NOT NULL AUTO_INCREMENT,
	confirmed BOOLEAN,
	email VARCHAR(255) NOT NULL,
	friend_email VARCHAR(255) NOT NULL,
	
	PRIMARY KEY(id_friendship)
) $$

-- LISTADO DE USUARIOS
DROP TABLE IF EXISTS Users $$
CREATE TABLE Users (
	email VARCHAR(255) NOT NULL,
	password VARCHAR(255) NOT NULL, 
	name VARCHAR(200),
	lastname VARCHAR(200),
	dpi BIGINT,
	photo VARCHAR(255),
	role INTEGER,
	
	PRIMARY KEY(email)	
) $$

-- LLAVES FORÁNEAS DE TABLA DE AMIGOS
ALTER TABLE Friends ADD FOREIGN KEY(email) REFERENCES Users(email) ON DELETE CASCADE $$
ALTER TABLE Friends ADD FOREIGN KEY(friend_email) REFERENCES Users(email) ON DELETE CASCADE $$
ALTER TABLE Friends ADD UNIQUE(email, friend_email) $$

-- LLAVES FORÁNEAS DE CHATS CON AMIGOS
ALTER TABLE Chat_friends ADD FOREIGN KEY(id_friendship) REFERENCES Friends(id_friendship) ON DELETE CASCADE $$

-- LLAVES FORÁNEAS DE CHATS CON BOTS
ALTER TABLE Chat_bots ADD FOREIGN KEY(email) REFERENCES Users(email) ON DELETE CASCADE $$

-- LLAVES FORÁNEAS DE PUBLICACIONES
ALTER TABLE Publications ADD FOREIGN KEY(email) REFERENCES Users(email) ON DELETE CASCADE $$

-- LLAVES FORÁNEAS DE COMENTARIOS
ALTER TABLE Comments ADD FOREIGN KEY(email) REFERENCES Users(email) ON DELETE SET NULL $$
ALTER TABLE Comments ADD FOREIGN KEY(pub_id) REFERENCES Publications(pub_id) ON DELETE CASCADE $$

-- LLAVES FORÁNEAS DEL DETALLE DE LOS TAGS
ALTER TABLE Tags_detail ADD FOREIGN KEY(pub_id) REFERENCES Publications(pub_id) ON DELETE CASCADE $$
ALTER TABLE Tags_detail ADD FOREIGN KEY(tag_id) REFERENCES Tags(tag_id) ON DELETE CASCADE $$